version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - uploads:/app/uploads
      - database:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_PATH=/app/data/heroes.sqlite
      - UPLOADS_PATH=/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "dist/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app-prod:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads
      - database:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/data/heroes.sqlite
      - UPLOADS_PATH=/app/uploads
    restart: unless-stopped
    profiles:
      - production

volumes:
  uploads:
    driver: local
  database:
    driver: local